version: "3.3"
services:
    mongo:
        image: mongo
        restart: always
        command: mongod --port 8090
        ports:
            - 8090:8090
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8091:8091
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_PORT: 8090
            VCAP_APP_HOST: 0.0.0.0
            VCAP_APP_PORT: 8091
      
    user-manager:
        image: sinthoma/user-manager
        ports:
            - 8092:8092
        links:
            - mongo
        entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
      