version: "3.3"
services:
    dynamodb:
      container_name: dynamodb
      image: amazon/dynamodb-local:latest
      volumes:
          - dynamodb-data:/data
      ports:
          - "8090:8090"  
      entrypoint: java
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
      restart: always
      
#    mongo:
#        image: mongo
#        restart: always
#        command: mongod --port 8090
#        ports:
#            - 8090:8090
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example
#
#    mongo-express:
#        image: mongo-express
#        restart: always
#        ports:
#            - 8091:8091
#        environment:
#            ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            ME_CONFIG_MONGODB_ADMINPASSWORD: example
#            ME_CONFIG_MONGODB_PORT: 8090
#            VCAP_APP_HOST: 0.0.0.0
#            VCAP_APP_PORT: 8091
      
#    user-manager:
#        image: shishirinsane/sinthoma/user-manager
#        ports:
#            - 8092:8092
#        links:
#            - mongo    
#        build:
#            context: ./service/user-manager
#            dockerfile: Dockerfile
            
#    sinthoma-bff:
#        image: shishirinsane/sinthoma/sinthoma-bff
#        ports:
#            - 8093:8093
#        links:
#            - user-manager    
#        build:
#            context: ./service/user-manager
#            dockerfile: Dockerfile

volumes:
    dynamodb-data:
        external: true