server:
  port: 8092
  servlet:
    context-path: /sinthoma/user-manager
spring:
  data:
    mongodb:
      uri: mongodb://app-owner:App0wn3r@mongo/sinthoma
    rest:
      default-page-size: 10
      max-page-size: 25
  application:
    name: user-manager
logging:
  file: ./user-manager.log
  level:
    com.sk.sinthoma.user: INFO
    org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE
    org.springframework: INFO        